export { default as SplitterGroup } from './SplitterGroup.vue'
export { default as SplitterPanel } from './SplitterPanel.vue'
export { default as SplitterResizeHandle } from './SplitterResizeHandle.vue'
export { splitterContextKey } from './Splitter.context'
export type { SplitterGroupContext } from './Splitter.context'
export type { SplitterVariants } from '@auronui/styles'
