import type { AlertDialogVariants } from "@auronui/styles";
import { createStrictContext } from "../../utils";

export type AlertDialogPlacement = "auto" | "top" | "center" | "bottom";

export interface AlertDialogContextValue {
  isOpen: boolean;
  open: () => void;
  close: () => void;
  toggle: () => void;
  size: AlertDialogVariants["size"];
  variant: AlertDialogVariants["variant"];
  placement: AlertDialogPlacement;
  status: AlertDialogVariants["status"];
  /** Stable id generated by the `AlertDialog` root, wired as `aria-describedby` on `Dialog` and as `id` on `AlertDialogDescription`. */
  descriptionId: string;
}

export const { Provider: AlertDialogProvider, useStrictContext: useAlertDialogContext } =
  createStrictContext<AlertDialogContextValue>("AlertDialog");
