import type { RefObject } from "react";
import type { ModalVariants } from "@auronui/styles";
import { createStrictContext } from "../../utils";

export type ModalPlacement = "auto" | "top" | "center" | "bottom";

export interface ModalContextValue {
  isOpen: boolean;
  open: () => void;
  close: () => void;
  toggle: () => void;
  /** Ref attached to the trigger element by <ModalTrigger>. */
  triggerRef: RefObject<HTMLElement | null>;
  size: ModalVariants["size"];
  scroll: ModalVariants["scroll"];
  variant: ModalVariants["variant"];
  placement: ModalPlacement;
  /** Stable id generated by the `Modal` root, wired as `aria-describedby` on `Dialog` and as `id` on `ModalDescription`. */
  descriptionId: string;
}

export const { Provider: ModalProvider, useStrictContext: useModalContext } =
  createStrictContext<ModalContextValue>("Modal");
